"""empty message

Revision ID: 17a75e043133
Revises: 1988b750bc69
Create Date: 2022-05-09 22:08:44.886027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a75e043133'
down_revision = '1988b750bc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collect_ibfk_1', 'collect', type_='foreignkey')
    op.drop_constraint('collect_ibfk_2', 'collect', type_='foreignkey')
    op.create_foreign_key(None, 'collect', 'cook', ['cook'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'collect', 'user', ['user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collect', type_='foreignkey')
    op.drop_constraint(None, 'collect', type_='foreignkey')
    op.create_foreign_key('collect_ibfk_2', 'collect', 'user', ['user'], ['id'])
    op.create_foreign_key('collect_ibfk_1', 'collect', 'cook', ['cook'], ['id'])
    # ### end Alembic commands ###
