"""empty message

Revision ID: 7e912638df6b
Revises: ea12a94897d1
Create Date: 2022-05-05 19:24:59.797104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e912638df6b'
down_revision = 'ea12a94897d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='cook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'cook', ['name'], unique=False)
    # ### end Alembic commands ###
