"""empty message

Revision ID: b677b2ec8f15
Revises: d2716ce27234
Create Date: 2022-01-27 13:21:47.833290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b677b2ec8f15'
down_revision = 'd2716ce27234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('eng_name', sa.String(length=100), nullable=False),
    sa.Column('method', sa.Enum('MIXING', 'BAKING', 'SIMMERING', 'KNEADING', 'BOILING', 'NOODLE', 'DEEP_FRYING', 'STIR_FRYING', 'PASTA', 'JAM', 'PIE', 'STEAMING', 'PIZZA', 'FERMENTING', 'SOUS_VIDE', 'JULIENNING', name='method'), nullable=False),
    sa.Column('ingredients', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cook')
    # ### end Alembic commands ###
