"""empty message

Revision ID: eec41a5bd802
Revises: 17a75e043133
Create Date: 2022-05-30 19:25:15.241054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec41a5bd802'
down_revision = '17a75e043133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_pw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=36), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_pw')
    # ### end Alembic commands ###
